# Automatically translated using m2cpp 2.0 on 2019-03-03 12:32:17
#
# encoding: utf-8
#
# Supplement file
#
# Valid inputs:
#
# uword   int     float   double cx_double
# uvec    ivec    fvec    vec    cx_vec
# urowvec irowvec frowvec rowvec cx_rowvec
# umat    imat    fmat    mat    cx_mat
# ucube   icube   fcube   cube   cx_cube
#
# char    string  struct  structs func_lambda

functions = {
  "MWHA" : {
            "A" : "mat",
            "B" : "mat",
         "HiLo" : "int",
            "V" : "mat",
           "YY" : "mat",
         "Y_mw" : "vec",
          "ang" : "vec",
          "cs1" : "vec",
          "cs2" : "vec",
           "d1" : "mat",
           "d2" : "mat",
           "di" : "mat",
       "diff11" : "",
       "diff12" : "",
       "diff13" : "",
       "diff14" : "",
       "diff21" : "",
       "diff22" : "",
       "diff31" : "",
       "diff32" : "",
      "diffVec" : "vec",
      "diff_yi" : "",
           "dm" : "int",
          "dm2" : "int",
          "dmi" : "int",
          "fet" : "double",
         "high" : "double",
        "i_num" : "int",
            "j" : "int",
           "lo" : "uvec",
          "lo1" : "",
          "lo2" : "uvec",
          "lo3" : "uvec",
     "lo_diff1" : "uvec",
        "lo_p1" : "uvec",
        "lo_p2" : "uvec",
        "lo_p3" : "uvec",
        "lo_p4" : "uvec",
        "lo_p5" : "uvec",
        "lo_p6" : "uvec",
       "lo_py1" : "uvec",
       "lo_py2" : "",
          "low" : "double",
            "m" : "int",
    "mat_mean1" : "",
    "mat_mean2" : "",
    "mat_mean3" : "",
    "max_y_err" : "vec",
           "nf" : "int",
       "nnodes" : "uword",
         "nout" : "uword",
      "noutmax" : "int",
      "npoints" : "uword",
        "num_0" : "uvec",
            "p" : "mat",
           "p1" : "",
           "p2" : "",
           "p3" : "",
           "p4" : "",
           "p5" : "",
           "p6" : "",
        "p_num" : "rowvec",
      "p_y_or1" : "",
      "p_y_or2" : "",
      "p_y_or3" : "",
      "p_y_or4" : "",
      "p_y_or5" : "",
         "p_yi" : "rowvec",
        "p_yi1" : "",
        "p_yi2" : "",
        "p_yi3" : "",
        "p_yi4" : "",
        "p_yi5" : "",
        "p_yi6" : "",
           "px" : "mat",
            "r" : "rowvec",
      "rankVec" : "",
          "sn1" : "vec",
          "sn2" : "vec",
         "temp" : "",
          "thr" : "double",
            "v" : "mat",
            "w" : "mat",
        "w_new" : "",
         "w_or" : "",
           "wi" : "int",
           "wj" : "int",
            "x" : "vec",
           "x1" : "vec",
           "xi" : "vec",
          "y_1" : "vec",
          "y_2" : "vec",
          "y_3" : "vec",
        "y_err" : "vec",
         "y_or" : "vec",
           "yi" : "vec",
          "yi1" : "vec",
          "yi2" : "vec",
  },
}
includes = [
  '#include "mconvert.h"',
  '#include <armadillo>',
  'using namespace arma ;',
]